version: '3.8'

services:
  app:
    build: .
    container_name: nestjs_blockchain
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8
    container_name: blockchain_app
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: blockchain_app
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
